Import('env')

env = env.Clone()

# lexy
env.Append(CPPPATH = '../common/contrib/lexy/include')
env.Append(CPPDEFINES = ['LEXY_HAS_UNICODE_DATABASE=1'])
lexy_sources = ['../common/contrib/lexy/src/input/file.cpp']

env.Program(target='parser', source=lexy_sources + ['parser.cpp'])
