on:
  pull_request:
  push:
    branches:
      - main
      - poc

name: continuous-integration

jobs:
  unix:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-22.04]
        cxx_compiler: [clang++-14]
        include:
          - platform: macos-latest
            cxx_compiler: "$(brew --prefix llvm@14)/bin/clang++"

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0

      - name: Install Linux dependencies
        if: ${{ matrix.platform == 'ubuntu-22.04' }}
        run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

      - name: Install macOS dependencies
        if: ${{ matrix.platform == 'macos-latest' }}
        run: brew install coreutils llvm

      - name: Configure
        run: cmake -GNinja -B build -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Test
        run: ./build/toolchain/parser/test-parser

  windows:
    strategy:
      fail-fast: true

    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0

      - name: Setup LLVM libraries
        shell: cmd
        run: |
          curl https://github.com/catalyst-lang/llvm-windows-builds/releases/download/llvmorg-15.0.4/llvmorg-15.0.4-dev-win64.zip --output llvm.zip
          7z x llvm.zip -o.

      - name: Configure CMake
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set LLVM_DIR=%GITHUB_WORKSPACE%\llvm-build\lib\cmake
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build build

      - name: Test
        run: |
          .\build\toolchain\parser\test-parser.exe
